apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: jfrog-xray
inputs:
  registry-url:
    required: true
  username:
    required: true
  password:
    required: true
  image-location:
    required: true
  image-tag:
    required: true
runs:
  using: composite
  steps:
    - id: jfrog-xray
      name: jfrog-xray
      uses: docker://registry.saas-dev.beescloud.com/staging/compliance-xray:main-14d118e2fe5b75e4509a73a003463af16159315e
      shell: bash
      env:
        RUN_ID: ${{ cloudbees.run_id }}
        JOB_ID: ${{ job.id }}
        STEP_ID: ${{ step.internal.id}}
        DNS_URL: ${{ cloudbees.api.url }}
        JWT_TOKEN: ${{ cloudbees.api.token }}
        BINARY_IMAGE_NAME: "xray_binary_asset.tar"
        CONFIG_JSON: '{\"metaInfo\":{\"url\":\"${{ inputs.registry-url }}\",\"username\":\"${{ inputs.username }}\",\"password\":\"${{ inputs.password }}\",\"client_secret\":\"NA\",\"scope\":\"${{ vars.JFROG_SCOPE }}\",\"toolName\":\"xray\"},\"orchestratorInfo\":{\"assetType\":\"BINARY\",\"assetIdentifier\":\"${{ inputs.image-location }}\",\"profileIdentifier\":\"${{ inputs.image-tag }}\"},\"metaInformation\":{\"actor\":\"${{ cloudbees.event.head_commit.author.username }}\",\"commit_id\":\"NA\",\"tenent_info\":\"NA\",\"scanner_type\":\"SCA\",\"pipeline_info\":{\"id\":\"04612\",\"name\":\"test_pipeline\",\"step_id\":\"04612_test_pipeline\"}}}'
      run: |
        set -x
        echo "RUN ID: ${{ cloudbees.run_id }}"
        echo "Job ID: ${{ job.id }}"
        echo "Step ID: ${{step.internal.id}}"
        cd /
        if [ -f $CLOUDBEES_WORKSPACE/$BINARY_IMAGE_NAME ]; then
          rm $CLOUDBEES_WORKSPACE/$BINARY_IMAGE_NAME
        fi
        crane flatten ${{ inputs.image-location }}:${{ inputs.image-tag }}
        skopeo copy docker://${{ inputs.image-location }}:${{ inputs.image-tag }} docker-archive:$CLOUDBEES_WORKSPACE/$BINARY_IMAGE_NAME:${{ inputs.image-location }}:${{ inputs.image-tag }}
        /bin/bash -c "java -jar ./executables/xray.jar & while ! nc -z localhost 5001; do sleep 1; done && ./executables/orchestrator -scanConfig \"${CONFIG_JSON}\" execute-analyser && exit"
