apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: jfrog-xray
inputs:
  registry-url:
    required: true
  username:
    required: true
  password:
    required: true
  image-location:
    required: true
  image-tag:
    required: true
runs:
  using: composite
  steps:
    - name: skopeo
      uses: docker://public.ecr.aws/logistics/quay.io/skopeo/stable:v1.10
      shell: bash
      env:
        BINARY_IMAGE_NAME: "xray_binary_asset.tar"
      run: | 
        set -x
        skopeo -v
        cd /
        if [ -f $CLOUDBEES_WORKSPACE/$BINARY_IMAGE_NAME ]; then
             rm $CLOUDBEES_WORKSPACE/$BINARY_IMAGE_NAME
        fi
        skopeo login -u ${{ inputs.username }} -p ${{ inputs.password }} https://${{ inputs.registry-url }}
        skopeo copy --insecure-policy docker://${{ inputs.image-location }}:${{ inputs.image-tag }} docker-archive:$CLOUDBEES_WORKSPACE/$BINARY_IMAGE_NAME:${{ inputs.image-location }}:${{ inputs.image-tag }} --dest-oci-accept-uncompressed-layers
        ls -ltr $CLOUDBEES_WORKSPACE

    - name: jfrog-xray
      uses: docker://public.ecr.aws/l7o7z1g8/actions/jfrog-xray-container-actions:main-636b7b28beea5d3c7357a712d7dbe984e108eac2
      shell: bash
      env:
        RUN_ID: ${{ cloudbees.run_id }}
        JOB_ID: ${{ job.id }}
        STEP_ID: ${{ step.internal.id}}
        DNS_URL: ${{ cloudbees.api.url }}
        JWT_TOKEN: ${{ cloudbees.api.token }}
        BINARY_IMAGE_NAME: "xray_binary_asset.tar"
        CONFIG_JSON: '{\"metaInfo\":{\"url\":\"${{ inputs.registry-url }}\",\"username\":\"${{ inputs.username }}\",\"password\":\"${{ inputs.password }}\",\"client_secret\":\"NA\",\"scope\":\"member-of-groups:readers\",\"toolName\":\"xray\"},\"orchestratorInfo\":{\"assetType\":\"BINARY\",\"assetIdentifier\":\"${{ inputs.image-location }}\",\"profileIdentifier\":\"${{ inputs.image-tag }}\"},\"metaInformation\":{\"actor\":\"SCM-Bot\",\"commit_id\":\"NA\",\"tenent_info\":\"NA\",\"scanner_type\":\"SCA\",\"pipeline_info\":{\"id\":\"04612\",\"name\":\"test_pipeline\",\"step_id\":\"04612_test_pipeline\"}}}'
      run: |
        set -x
        echo "RUN ID: ${{ cloudbees.run_id }}"
        echo "Job ID: ${{ job.id }}"
        echo "Step ID: ${{step.internal.id}}"
        cd /

        /bin/bash -c "java -jar ./executables/xray.jar & while ! nc -z localhost 5001; do sleep 1; done && ./executables/orchestrator -scanConfig \"${CONFIG_JSON}\" execute-analyser && exit"
